create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon, authenticated;

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 40),
  title text not null check (char_length(trim(title)) between 1 and 120),
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.board_posts
  add column if not exists delete_password_hash text;

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

create table if not exists public.board_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.board_posts (id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 40),
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists board_comments_post_id_created_at_idx
  on public.board_comments (post_id, created_at);

create table if not exists private.board_admins (
  email text primary key
);

comment on table private.board_admins is
  'Insert one row per admin email after creating that user in Supabase Auth.';

alter table public.board_posts enable row level security;
alter table public.board_comments enable row level security;

grant usage on schema public to anon, authenticated;

revoke all on table public.board_posts from anon, authenticated;
revoke all on table public.board_comments from anon, authenticated;
revoke all on table private.board_admins from anon, authenticated;
revoke all on sequence public.board_posts_id_seq from anon, authenticated;
revoke all on sequence public.board_comments_id_seq from anon, authenticated;

grant select (id, name, title, content, created_at)
  on table public.board_posts
  to anon, authenticated;

grant select (id, post_id, name, content, created_at)
  on table public.board_comments
  to anon, authenticated;

grant delete on table public.board_posts to authenticated;
grant delete on table public.board_comments to authenticated;

drop policy if exists "Public can read board posts" on public.board_posts;
drop policy if exists "Public can insert board posts" on public.board_posts;
drop policy if exists "Admins can delete board posts" on public.board_posts;
drop policy if exists "Public can read board comments" on public.board_comments;
drop policy if exists "Admins can delete board comments" on public.board_comments;

create or replace function private.is_board_admin()
returns boolean
language sql
stable
security definer
set search_path = private, public, pg_temp
as $$
  select exists (
    select 1
    from private.board_admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function private.is_board_admin() from public;
revoke all on function private.is_board_admin() from anon, authenticated;

create policy "Public can read board posts"
on public.board_posts
for select
to anon, authenticated
using (true);

create policy "Admins can delete board posts"
on public.board_posts
for delete
to authenticated
using ((select private.is_board_admin()));

create policy "Public can read board comments"
on public.board_comments
for select
to anon, authenticated
using (true);

create policy "Admins can delete board comments"
on public.board_comments
for delete
to authenticated
using ((select private.is_board_admin()));

create or replace function public.is_board_admin_session()
returns boolean
language sql
stable
security definer
set search_path = public, private, pg_temp
as $$
  select private.is_board_admin();
$$;

create or replace function public.create_board_post(
  p_name text,
  p_title text,
  p_content text,
  p_delete_password text
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_name text := trim(coalesce(p_name, ''));
  v_title text := trim(coalesce(p_title, ''));
  v_content text := trim(coalesce(p_content, ''));
  v_delete_password text := coalesce(p_delete_password, '');
  v_post_id bigint;
begin
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'Name must be between 1 and 40 characters.';
  end if;

  if char_length(v_title) < 1 or char_length(v_title) > 120 then
    raise exception 'Title must be between 1 and 120 characters.';
  end if;

  if char_length(v_content) < 1 or char_length(v_content) > 2000 then
    raise exception 'Message must be between 1 and 2000 characters.';
  end if;

  if char_length(v_delete_password) < 4 or char_length(v_delete_password) > 72 then
    raise exception 'Delete password must be between 4 and 72 characters.';
  end if;

  insert into public.board_posts (name, title, content, delete_password_hash)
  values (
    v_name,
    v_title,
    v_content,
    extensions.crypt(v_delete_password, extensions.gen_salt('bf'))
  )
  returning id into v_post_id;

  return v_post_id;
end;
$$;

create or replace function public.create_board_comment(
  p_post_id bigint,
  p_name text,
  p_content text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_name text := trim(coalesce(p_name, ''));
  v_content text := trim(coalesce(p_content, ''));
  v_comment_id bigint;
begin
  if p_post_id is null then
    raise exception 'A valid post id is required.';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'Comment name must be between 1 and 40 characters.';
  end if;

  if char_length(v_content) < 1 or char_length(v_content) > 1000 then
    raise exception 'Comment must be between 1 and 1000 characters.';
  end if;

  if not exists (
    select 1
    from public.board_posts
    where id = p_post_id
  ) then
    raise exception 'Post not found.';
  end if;

  insert into public.board_comments (post_id, name, content)
  values (p_post_id, v_name, v_content)
  returning id into v_comment_id;

  return v_comment_id;
end;
$$;

create or replace function public.delete_board_post_with_password(
  p_post_id bigint,
  p_delete_password text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_deleted_count integer;
begin
  if p_post_id is null then
    raise exception 'A valid post id is required.';
  end if;

  if char_length(coalesce(p_delete_password, '')) < 4 then
    raise exception 'Delete password must be at least 4 characters.';
  end if;

  delete from public.board_posts
  where id = p_post_id
    and delete_password_hash is not null
    and delete_password_hash = extensions.crypt(p_delete_password, delete_password_hash);

  get diagnostics v_deleted_count = row_count;
  return v_deleted_count = 1;
end;
$$;

revoke all on function public.is_board_admin_session() from public;
revoke all on function public.create_board_post(text, text, text, text) from public;
revoke all on function public.create_board_comment(bigint, text, text) from public;
revoke all on function public.delete_board_post_with_password(bigint, text) from public;

grant execute on function public.is_board_admin_session() to anon, authenticated;
grant execute on function public.create_board_post(text, text, text, text) to anon, authenticated;
grant execute on function public.create_board_comment(bigint, text, text) to anon, authenticated;
grant execute on function public.delete_board_post_with_password(bigint, text) to anon, authenticated;

-- After creating an Auth user in Supabase, allow that user to moderate the board:
-- insert into private.board_admins (email)
-- values ('your-admin-email@example.com')
-- on conflict (email) do nothing;
