create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 40),
  title text not null check (char_length(trim(title)) between 1 and 120),
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

alter table public.board_posts enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.board_posts to anon, authenticated;
grant usage, select on sequence public.board_posts_id_seq to anon, authenticated;

drop policy if exists "Public can read board posts" on public.board_posts;
create policy "Public can read board posts"
on public.board_posts
for select
to anon, authenticated
using (true);

drop policy if exists "Public can insert board posts" on public.board_posts;
create policy "Public can insert board posts"
on public.board_posts
for insert
to anon, authenticated
with check (true);
